### ISSUE TITLE
Native game model lose their facial expression after conversion

### ISSUE THREAD

**Issue by CarlVerce** [Fothsid/OBTool#1]
When the tool is used with a native model of Outbreak, the converted model works correctly but the model doesn't have the facial expression anymore. 

Steps to reproduce:
- Take an original NBD from Outbreak
- Convert it to FBx
- Open it in Maya 2020
- Export the FBX with default settings
- Convert to NBD
- Import

Model tested: P07_04, N52, P00_00

**Comment by Fothsid** [comment]
Was able to reproduce the issue.

For some obscure reason, when importing Node22, Maya resets its Group ID parameter to 0, while it should be 2.
And I know that it's an issue with Maya because if I just convert the FBX that OBTool produced, the facial animations stay intact.
Also, if you manually edit the group id for Node22 in the NBD with broken facial animations, it fixes the issue.

**Comment by Fothsid** [comment]
My current hunch is that Maya doesn't load user properties correctly if a node with a skeleton attribute isn't referenced in any of the skin clusters.

**Comment by Fothsid** [comment]
More weird things from Maya!

In the original NBD, Node22 isn't even a skeleton joint! It's just a regular transformation node
Why does Maya give it a skeleton attribute at all?

**Comment by CarlVerce** [comment]
Can this issue affect models with more nodes? Like P07_00? Also, I will try with 3DS max. From what I'm reading it keep everything okay. 
Also I only use 3DS max and little of Blender, this is the first time that I'm using Maya.

**Comment by Fothsid** [comment]
It does affect P07_00.
More over, for P07_00 it affects not only Node22, but also Node38, which should have group id of 6, but Maya resets it to 0.

Soon will push a commit with a hacky change which will force non-skeleton nodes that are children of a skeleton node to have a skeleton attribute as well.

**Comment by Fothsid** [comment]
https://github.com/Fothsid/OBTool/releases/tag/v0.0.2-2

**Comment by CarlVerce** [comment]
I can confirm that with the new release (0.0.2-2) the facial expression works!
