### ISSUE TITLE
Shader problem

### ISSUE THREAD

**Issue by leonifc331** [Fothsid/OBTool#3]
hi, the models I convert are affected by lights more than the original models in the game. Do you know what can cause this?
![2021-08-21 (13)](https://user-images.githubusercontent.com/37820098/130362315-08097698-1721-49dd-b603-6efab2f63bc9.png)

**Comment by Fothsid** [comment]
Your material in the FBX has a very high ambient value.

**Comment by leonifc331** [comment]
> 
> 
> Your material in the FBX has a very high ambient value.

oh, thank you so much
